/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.*;
import Vista.FDMRegistro;
import java.awt.Graphics;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author campv
 */
public class FDMDatosConsulta extends javax.swing.JFrame {
    
    FondoPanel fondo = new FondoPanel();

    public static ArrayList<Registro> listaRegistros= new ArrayList<Registro>();
    /**
     * Creates new form FDMDatosConsulta
     */
    public FDMDatosConsulta() {
        
        this. setContentPane(fondo);
        
        initComponents();
        
        btnGuardar.setToolTipText("Guardar y salir");
        btnGuardar.setPressedIcon(setIconoPresionado("Banner5.png",btnGuardar,50,50));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTelefonoVet = new javax.swing.JLabel();
        txtTelefonoVeterinario = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        lbClaveEmp = new javax.swing.JLabel();
        lbNombreCompletoVeterinario = new javax.swing.JLabel();
        txtClaveEmp = new javax.swing.JTextField();
        lbSaldo = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JTextField();
        lbCita = new javax.swing.JLabel();
        lbFecha = new javax.swing.JLabel();
        txtDia = new javax.swing.JTextField();
        lbTelefonoCliente = new javax.swing.JLabel();
        lbSlash1 = new javax.swing.JLabel();
        txtTelefonoCliente = new javax.swing.JTextField();
        txtMes = new javax.swing.JTextField();
        lbDomicilio = new javax.swing.JLabel();
        lbSlash2 = new javax.swing.JLabel();
        txtDomicilio = new javax.swing.JTextField();
        txtAnio = new javax.swing.JTextField();
        lbVeterinario = new javax.swing.JLabel();
        lbHora = new javax.swing.JLabel();
        lbNombreCliente = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        txtNombreVeterinario = new javax.swing.JTextField();
        lbDosPuntos = new javax.swing.JLabel();
        txtApellidoPveterinario = new javax.swing.JTextField();
        txtMinutos = new javax.swing.JTextField();
        lbApellidoPvet = new javax.swing.JLabel();
        lbApellidoMvet = new javax.swing.JLabel();
        lbNombreCompletoCliente = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        txtApellidoPcliente = new javax.swing.JTextField();
        lbApellidoPcliente = new javax.swing.JLabel();
        lbApellidoMcliente = new javax.swing.JLabel();
        txtApellidoMcliente = new javax.swing.JTextField();
        lbCliente = new javax.swing.JLabel();
        lbDuracion = new javax.swing.JLabel();
        txtDuracion = new javax.swing.JTextField();
        txtApellidoMveterinario = new javax.swing.JTextField();
        lbCostoBase = new javax.swing.JLabel();
        lbNombreVet = new javax.swing.JLabel();
        txtCostoBase = new javax.swing.JTextField();
        lbTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(564, 710));
        setResizable(false);

        lbTelefonoVet.setBackground(new java.awt.Color(165, 137, 119));
        lbTelefonoVet.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbTelefonoVet.setText("Núm. de telefono:");
        lbTelefonoVet.setOpaque(true);

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Banner5.png"))); // NOI18N
        btnGuardar.setBorder(null);
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setDefaultCapable(false);
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        lbClaveEmp.setBackground(new java.awt.Color(165, 137, 119));
        lbClaveEmp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbClaveEmp.setText("Clave de empleado:");
        lbClaveEmp.setOpaque(true);

        lbNombreCompletoVeterinario.setBackground(new java.awt.Color(165, 137, 119));
        lbNombreCompletoVeterinario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbNombreCompletoVeterinario.setText("Nombre completo:");
        lbNombreCompletoVeterinario.setOpaque(true);

        lbSaldo.setBackground(new java.awt.Color(165, 137, 119));
        lbSaldo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbSaldo.setText("Saldo:");
        lbSaldo.setOpaque(true);

        lbCita.setBackground(new java.awt.Color(165, 137, 119));
        lbCita.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lbCita.setText("Cita:");
        lbCita.setOpaque(true);

        lbFecha.setBackground(new java.awt.Color(165, 137, 119));
        lbFecha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbFecha.setText("Fecha(dd/mm/aaaa):");
        lbFecha.setOpaque(true);

        lbTelefonoCliente.setBackground(new java.awt.Color(165, 137, 119));
        lbTelefonoCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbTelefonoCliente.setText("Núm. de telefono:");
        lbTelefonoCliente.setOpaque(true);

        lbSlash1.setBackground(new java.awt.Color(165, 137, 119));
        lbSlash1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbSlash1.setText("/");
        lbSlash1.setOpaque(true);

        lbDomicilio.setBackground(new java.awt.Color(165, 137, 119));
        lbDomicilio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbDomicilio.setText("Domicilio:");
        lbDomicilio.setOpaque(true);

        lbSlash2.setBackground(new java.awt.Color(165, 137, 119));
        lbSlash2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbSlash2.setText("/");
        lbSlash2.setOpaque(true);

        lbVeterinario.setBackground(new java.awt.Color(165, 137, 119));
        lbVeterinario.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lbVeterinario.setText("Veterinario atendiendo:");
        lbVeterinario.setOpaque(true);

        lbHora.setBackground(new java.awt.Color(165, 137, 119));
        lbHora.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbHora.setText("Hora de cita:");
        lbHora.setOpaque(true);

        lbNombreCliente.setBackground(new java.awt.Color(165, 137, 119));
        lbNombreCliente.setText("Nombre");
        lbNombreCliente.setOpaque(true);

        txtNombreVeterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreVeterinarioActionPerformed(evt);
            }
        });

        lbDosPuntos.setBackground(new java.awt.Color(165, 137, 119));
        lbDosPuntos.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lbDosPuntos.setText(":");
        lbDosPuntos.setOpaque(true);

        lbApellidoPvet.setBackground(new java.awt.Color(165, 137, 119));
        lbApellidoPvet.setText("Apellido paterno");
        lbApellidoPvet.setOpaque(true);

        lbApellidoMvet.setBackground(new java.awt.Color(165, 137, 119));
        lbApellidoMvet.setText("Apellido materno");
        lbApellidoMvet.setOpaque(true);

        lbNombreCompletoCliente.setBackground(new java.awt.Color(165, 137, 119));
        lbNombreCompletoCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbNombreCompletoCliente.setText("Nombre completo:");
        lbNombreCompletoCliente.setOpaque(true);

        txtNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreClienteActionPerformed(evt);
            }
        });

        lbApellidoPcliente.setBackground(new java.awt.Color(165, 137, 119));
        lbApellidoPcliente.setText("Apellido paterno");
        lbApellidoPcliente.setOpaque(true);

        lbApellidoMcliente.setBackground(new java.awt.Color(165, 137, 119));
        lbApellidoMcliente.setText("Apellido materno");
        lbApellidoMcliente.setOpaque(true);

        lbCliente.setBackground(new java.awt.Color(165, 137, 119));
        lbCliente.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lbCliente.setText("Cliente:");
        lbCliente.setOpaque(true);

        lbDuracion.setBackground(new java.awt.Color(165, 137, 119));
        lbDuracion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbDuracion.setText("Duración(horas):");
        lbDuracion.setOpaque(true);

        lbCostoBase.setBackground(new java.awt.Color(165, 137, 119));
        lbCostoBase.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbCostoBase.setText("Costo base:");
        lbCostoBase.setOpaque(true);

        lbNombreVet.setBackground(new java.awt.Color(165, 137, 119));
        lbNombreVet.setText("Nombre");
        lbNombreVet.setOpaque(true);

        txtCostoBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostoBaseActionPerformed(evt);
            }
        });

        lbTitulo.setBackground(new java.awt.Color(165, 137, 119));
        lbTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Titulo3.png"))); // NOI18N
        lbTitulo.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbNombreCompletoCliente)
                                        .addComponent(lbTelefonoCliente)
                                        .addComponent(lbDomicilio))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtApellidoPcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtApellidoMcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txtDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lbSaldo)
                                                .addComponent(lbClaveEmp)
                                                .addComponent(lbTelefonoVet))
                                            .addGap(24, 24, 24)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtTelefonoVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(txtSaldo, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtClaveEmp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lbFecha)
                                                .addComponent(lbHora)
                                                .addComponent(lbDuracion)
                                                .addComponent(lbCostoBase))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(lbSlash1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(lbSlash2, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lbCita)
                                                        .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(lbDosPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(txtCostoBase, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(lbNombreCompletoVeterinario)
                                            .addGap(28, 28, 28)
                                            .addComponent(txtNombreVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtApellidoPveterinario, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtApellidoMveterinario, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(1, 1, 1)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(183, 183, 183)
                                .addComponent(lbNombreCliente)
                                .addGap(59, 59, 59)
                                .addComponent(lbApellidoPcliente)
                                .addGap(27, 27, 27)
                                .addComponent(lbApellidoMcliente))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbVeterinario)
                                .addGap(89, 89, 89))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbCliente)
                                .addGap(150, 150, 150))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnGuardar)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbNombreVet)
                                        .addGap(58, 58, 58)
                                        .addComponent(lbApellidoPvet)
                                        .addGap(29, 29, 29)
                                        .addComponent(lbApellidoMvet)))
                                .addGap(20, 20, 20)))))
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(lbTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombreCompletoCliente)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidoPcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidoMcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbApellidoPcliente)
                    .addComponent(lbNombreCliente)
                    .addComponent(lbApellidoMcliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTelefonoCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDomicilio)
                    .addComponent(txtDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(lbVeterinario)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombreCompletoVeterinario)
                    .addComponent(txtNombreVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidoPveterinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidoMveterinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbApellidoPvet)
                    .addComponent(lbApellidoMvet)
                    .addComponent(lbNombreVet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTelefonoVet)
                    .addComponent(txtTelefonoVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbClaveEmp)
                    .addComponent(txtClaveEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSaldo))
                .addGap(18, 18, 18)
                .addComponent(lbCita)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFecha)
                    .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSlash1)
                    .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSlash2)
                    .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHora)
                    .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDosPuntos)
                    .addComponent(txtMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbDuracion)
                            .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbCostoBase)
                            .addComponent(txtCostoBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnGuardar))
                .addGap(160, 160, 160))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreVeterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreVeterinarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreVeterinarioActionPerformed

    private void txtNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreClienteActionPerformed

    private void txtCostoBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostoBaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoBaseActionPerformed

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        // TODO add your handling code here:
        try{
            
        
        //dueño
        String nombreC= txtNombreCliente.getText();
        String apellidoPC= txtApellidoPcliente.getText();
        String apellidoMC= txtApellidoMcliente.getText();
        String telefonoC= txtTelefonoCliente.getText();
        String domicilio= txtDomicilio.getText();
        
        Dueno unDueno= new Dueno(nombreC,apellidoPC,apellidoMC,telefonoC,domicilio);
        
        //veterinario
        String nombreV= txtNombreVeterinario.getText();
        String apellidoPV= txtApellidoPveterinario.getText();
        String apellidoMV= txtApellidoMveterinario.getText();
        String telefonoV=txtTelefonoVeterinario.getText();
        String claveEmp= txtClaveEmp.getText();
        double saldo= Double.parseDouble(txtSaldo.getText());
        
        Veterinario unVeterinario= new Veterinario(nombreV,apellidoPV,apellidoMV,telefonoV,saldo,claveEmp);
        
        //cita
        int dia=Integer.parseInt(txtDia.getText());
        int mes=Integer.parseInt(txtMes.getText());
        int anio=Integer.parseInt(txtAnio.getText());
        
        Fecha unaFecha= new Fecha(dia,mes,anio);
        
        int hora=Integer.parseInt(txtHora.getText());
        int minutos=Integer.parseInt(txtMinutos.getText());
        
        Hora unaHora= new Hora(hora,minutos);
        
        int duracion= Integer.parseInt(txtDuracion.getText());
        double costoBase= Double.parseDouble(txtCostoBase.getText());
        
        Cita unaCita= new Cita(unaFecha,unaHora,duracion,costoBase);
        
        Registro unRegistro= new Registro(unDueno,unVeterinario,FDMMascotas.listaPerros,unaCita);
        
        listaRegistros.add(unRegistro);
        
        System.out.println("\n");
        for(int i=0;i<listaRegistros.size();i++){
            System.out.println(listaRegistros.get(i));
        }
        
        JOptionPane.showMessageDialog(rootPane, "Costo total de la cita:" + unaCita.calcularCostoCita(FDMMascotas.contador, saldo));

        FDMMascotas.contador = 0;
        FDMMascotas.listaPerros = new ArrayList<Perro>();
        this.dispose();
        
        // Abre la interfaz FDMRegistro
        FDMRegistro fdmRegistro = new FDMRegistro();
        fdmRegistro.setVisible(true);
        
        //Abre la interfaz FDMRegistro
        FDMTablaPerros fdmPerros= new FDMTablaPerros();
        fdmPerros.setVisible(true);
        }
        catch(NumberFormatException e1){
            JOptionPane.showMessageDialog(rootPane, "ERROR: dato inválido, Intente de nuevo");
        }
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel lbApellidoMcliente;
    private javax.swing.JLabel lbApellidoMvet;
    private javax.swing.JLabel lbApellidoPcliente;
    private javax.swing.JLabel lbApellidoPvet;
    private javax.swing.JLabel lbCita;
    private javax.swing.JLabel lbClaveEmp;
    private javax.swing.JLabel lbCliente;
    private javax.swing.JLabel lbCostoBase;
    private javax.swing.JLabel lbDomicilio;
    private javax.swing.JLabel lbDosPuntos;
    private javax.swing.JLabel lbDuracion;
    private javax.swing.JLabel lbFecha;
    private javax.swing.JLabel lbHora;
    private javax.swing.JLabel lbNombreCliente;
    private javax.swing.JLabel lbNombreCompletoCliente;
    private javax.swing.JLabel lbNombreCompletoVeterinario;
    private javax.swing.JLabel lbNombreVet;
    private javax.swing.JLabel lbSaldo;
    private javax.swing.JLabel lbSlash1;
    private javax.swing.JLabel lbSlash2;
    private javax.swing.JLabel lbTelefonoCliente;
    private javax.swing.JLabel lbTelefonoVet;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbVeterinario;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtApellidoMcliente;
    private javax.swing.JTextField txtApellidoMveterinario;
    private javax.swing.JTextField txtApellidoPcliente;
    private javax.swing.JTextField txtApellidoPveterinario;
    private javax.swing.JTextField txtClaveEmp;
    private javax.swing.JTextField txtCostoBase;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextField txtDomicilio;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtMes;
    private javax.swing.JTextField txtMinutos;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtNombreVeterinario;
    private javax.swing.JTextField txtSaldo;
    private javax.swing.JTextField txtTelefonoCliente;
    private javax.swing.JTextField txtTelefonoVeterinario;
    // End of variables declaration//GEN-END:variables

    class FondoPanel extends JPanel{
        private Image imagen;
        
        @Override
        public void paint(Graphics g){
           imagen = new ImageIcon(getClass().getResource("FondoDatosConsulta.png")).getImage();
           g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
           
           setOpaque(false);
           
           super.paint(g);
        }
    }
    
    public Icon setIcono(String url, JButton boton){
        ImageIcon icon = new ImageIcon(getClass().getResource(url));
        int ancho = boton.getWidth();
        int alto = boton.getHeight();
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));
        return icono;
    }
    
    public Icon setIconoPresionado(String url,JButton boton,int ancho,int altura){
        ImageIcon icon = new ImageIcon(getClass().getResource(url));
        int width = boton.getWidth() - ancho;
        int height = boton.getHeight() - altura;
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(width, height, Image.SCALE_DEFAULT));
        return icono;
    }

}
