/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.BorderLayout;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;


/**
 *
 * @author campv
 */
public class FDMInicioVeterinaria extends javax.swing.JFrame {
    
    FondoPanel fondo = new FondoPanel();
   

    /**
     * Creates new form InicioVeterinaria
     */
    public FDMInicioVeterinaria() {
        
        this. setContentPane(fondo);
        
        initComponents();
        

        setLocationRelativeTo(null);

        // Establecer la ubicación manualmente
        btSalir.setBounds(470, 35, 150, 100);

        // Desactivar el diseño automático (null layout)
        setLayout(null);

        // Agregar el botón al JFrame
        add(btSalir);
        
        // Configurar otras propiedades del botón
        // Puedes configurar el texto, el color de fondo, el color del texto, etc.
        btSalir.setToolTipText("Haz clic para salir");
        btSalir.setPressedIcon(setIconoPresionado("Banner1.png",btSalir,50,50));
        
        
        // Manejar eventos de redimensionamiento
        addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                // Ajustar la posición del botón al redimensionar la ventana
                int nuevaX = 470;
                int nuevaY = 35;
                btSalir.setBounds(nuevaX, nuevaY, 150, 110);
            }
        });
        
        // Hacer visible la ventana
        //setVisible(true);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        menuBarVeterinaria = new javax.swing.JMenuBar();
        menuConsulta = new javax.swing.JMenu();
        menuItemAgregarConsulta = new javax.swing.JMenuItem();
        menuRegistros = new javax.swing.JMenu();
        menuItemCitas = new javax.swing.JMenuItem();
        menuItemMascotas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Banner1.png"))); // NOI18N
        btSalir.setBorder(null);
        btSalir.setBorderPainted(false);
        btSalir.setContentAreaFilled(false);
        btSalir.setDefaultCapable(false);
        btSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSalirMouseClicked(evt);
            }
        });
        getContentPane().add(btSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, -1, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Titulo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        menuBarVeterinaria.setBackground(new java.awt.Color(204, 204, 255));
        menuBarVeterinaria.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255)));
        menuBarVeterinaria.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuBarVeterinaria.setName(""); // NOI18N
        menuBarVeterinaria.setOpaque(true);
        menuBarVeterinaria.setRequestFocusEnabled(false);
        menuBarVeterinaria.setVerifyInputWhenFocusTarget(false);

        menuConsulta.setText("Consultas");

        menuItemAgregarConsulta.setText("Agregar consulta");
        menuItemAgregarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAgregarConsultaActionPerformed(evt);
            }
        });
        menuConsulta.add(menuItemAgregarConsulta);

        menuBarVeterinaria.add(menuConsulta);

        menuRegistros.setBackground(new java.awt.Color(204, 204, 255));
        menuRegistros.setText("Registros");

        menuItemCitas.setText("Citas");
        menuItemCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCitasActionPerformed(evt);
            }
        });
        menuRegistros.add(menuItemCitas);

        menuItemMascotas.setText("Mascotas");
        menuItemMascotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemMascotasActionPerformed(evt);
            }
        });
        menuRegistros.add(menuItemMascotas);

        menuBarVeterinaria.add(menuRegistros);

        setJMenuBar(menuBarVeterinaria);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemAgregarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAgregarConsultaActionPerformed
        // TODO add your handling code here:
        new FDMMascotas().setVisible(true);
    }//GEN-LAST:event_menuItemAgregarConsultaActionPerformed

    private void menuItemCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCitasActionPerformed
        // TODO add your handling code here:
        new FDMRegistro().setVisible(true);
    }//GEN-LAST:event_menuItemCitasActionPerformed

    private void menuItemMascotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemMascotasActionPerformed
        // TODO add your handling code here:
        new FDMTablaPerros().setVisible(true);
    }//GEN-LAST:event_menuItemMascotasActionPerformed

    private void btSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSalirMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btSalirMouseClicked

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FDMInicioVeterinaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FDMInicioVeterinaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FDMInicioVeterinaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FDMInicioVeterinaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FDMInicioVeterinaria().setVisible(true);
            }
        });
    }
    
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar menuBarVeterinaria;
    private javax.swing.JMenu menuConsulta;
    private javax.swing.JMenuItem menuItemAgregarConsulta;
    private javax.swing.JMenuItem menuItemCitas;
    private javax.swing.JMenuItem menuItemMascotas;
    private javax.swing.JMenu menuRegistros;
    // End of variables declaration//GEN-END:variables
    
    class FondoPanel extends JPanel{
        private Image imagen;
        
        @Override
        public void paint(Graphics g){
           imagen = new ImageIcon(getClass().getResource("FondoInicio.png")).getImage();
           g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
           
           setOpaque(false);
           
           super.paint(g);
        }
    }

    public Icon setIcono(String url, JButton boton){
        ImageIcon icon = new ImageIcon(getClass().getResource(url));
        int ancho = boton.getWidth();
        int alto = boton.getHeight();
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));
        return icono;
    }
    
    public Icon setIconoPresionado(String url,JButton boton,int ancho,int altura){
        ImageIcon icon = new ImageIcon(getClass().getResource(url));
        int width = boton.getWidth() - ancho;
        int height = boton.getHeight() - altura;
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(width, height, Image.SCALE_DEFAULT));
        return icono;
    }

}
